### ISSUE TITLE
how to choose arrival rate?

### ISSUE THREAD

**Issue by chptx** [paridhika/Parking_Results#1]
Hello!
According to the result，with 20% server utility，CoAP GET/PUT arrival rate(λ1, λ2) is (1.1, 1.2), but MQTT is (37.7, 37.8), and so on,  why is the difference so significant?  according what to choose these values?

**Comment by paridhika** [comment]
Hello,

Thanks for your interest in my project. Actually, the arrival rate (λ1, λ2) can be anything. They just have to be approximately equal to ensure both GET and PUT requests are equal in number. There can be various combinations of arrival rate(λ1, λ2) in each case. The only thing that has to be ensured is blocking probability is zero. ie. the parking space is never completely filled and there is always some spot for the new arrival.
Let me know if this clarifies your question.

**Comment by chptx** [comment]
Does utilization of the server (20%, 40% etc.)  related to these arrival rate?  Does the λ values be calculated from the utilization? Thanks!

**Comment by paridhika** [comment]
Yes, λ1/μ1 +λ2/μ2 + η/μ3 corresponds to server utilization.  So values of  (λ1, λ2) have to be chosen to get the required server utilization.  You can refer my paper "[A Comparison of IoT application layer protocols
through a smart parking implementation](https://people.engr.ncsu.edu/hp/papers/Paridhika.pdf)" for more details. Thanks!

**Comment by chptx** [comment]
OK,  It is really helpful to me,  Thank you again!
